baseURL = "https://www.javinr.es/"
languageCode = "es-ES"
title = "Javier Nu침o Rosal Site"
theme = "indigo"

[params]
 Author = "Javier Nu침o Rosal"
 Biography = "Ingeniero Inform치tico en Capgemini. Geek (nicnac seg칰n novia-ahora-esposa ;-)). Fan del balonmano. Muchas otras funciones... la mejor: pap치"
 Avatar = "images/GabinoFanhunter.svg"
 ShowBio = true
 PermalinkText = "游댕"
 EmailAddress = "javinr@gmail.com"
 FacebookUser = "javinr"
 FlickrUser = "javinr"
 GitHubUser = "javinr"
 LinkedInUser = "javinr"
 TwitterUser = "nosoynuno"
 InstagramUser = "javinr"
 # These are parameters used for indieweb identity. You should set these along
 # with the above email/social network parameters.
[params.indieWeb]
 EmailAddress = "javinr@gmail.com"
 FacebookUser = "javinr"
 FlickrUser = "javinr"
 GitHubUser = "javinr"
 LinkedInUser = "javinr"
 TwitterUser = "nosoynuno"
 InstagramUser = "javinr"
 Country = "Espa침a"
 City = "Langreo"
 [params.endpoints]
   Auth = "https://indieauth.com/auth"
   Token = "https://tokens.indieauth.com/token"
   # To get webmention support, just register at webmention.io and paste the link for endpoint here.
   Webmention = "https://webmention.io/www.javinr.es/webmention"
   # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
   # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
   # It will probably require some PHP hackery though, as it's fairly basic.
   # Micropub = "https://www.javinr.es/nanopub/nanopub.php"
