
baseURL = "https://www.javinr.es/"
languageCode = "es-ES"
title = "Javier Nu침o Rosal"
theme = "ananke"
resourceDir = "./resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"
  [languages.es]
    title = "Mi blog"
    weight = 2
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/nosoynuno"
  instagram = ""
  youtube = ""
  github = "https://github.com/javinr"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

#[markup.goldmark.renderer]
# unsafe = true

#[params]
# Author = "Javier Nu침o Rosal"
# Biography = "Ingeniero Inform치tico en Capgemini. Geek (nicnac seg칰n novia-ahora-esposa ;-)). Fan del balonmano. Muchas otras funciones... la mejor: pap치"
# Avatar = "images/GabinoFanhunter.svg"
# ShowBio = true
# PermalinkText = "游댕"
# mainSections = ["post", "update"]
# EmailAddress = "javinr@gmail.com"
# FacebookUser = "javinr"
# FlickrUser = "javinr"
# GitHubUser = "javinr"
# TwitterUser = "nosoynuno"
# LinkedInUser = "javinr"
# InstagramUser = "javinr"
 # These are parameters used for indieweb identity. You should set these along
 # with the above email/social network parameters.
#[params.indieWeb]
# EmailAddress = "javinr@gmail.com"
# FacebookUser = "javinr"
# FlickrUser = "javinr"
# GitHubUser = "javinr"
# LinkedInUser = "javinr"
# TwitterUser = "nosoynuno"
# InstagramUser = "javinr"
# Country = "Espa침a"
# City = "Langreo"
# [params.endpoints]
#   Auth = "https://indieauth.com/auth"
#   Token = "https://tokens.indieauth.com/token"
   # To get webmention support, just register at webmention.io and paste the link for endpoint here.
#   Webmention = "https://webmention.io/www.javinr.es/webmention"
   # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
   # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
   # It will probably require some PHP hackery though, as it's fairly basic.
   # Micropub = "https://www.javinr.es/nanopub/nanopub.php"
