baseURL = "http://www.javinr.es/"
languageCode = "es-ES"
title = "Javier Nu침o Rosal Site"
theme = "indigo"

[params]
 Author = "Javier Nu침o Rosal"
 Biography = "Ingeniero Inform치tico en Capgemini. Geek (nicnac seg칰n novia-ahora-esposa ;-)). Fan del balonmano. Muchas otras funciones... la mejor: pap치"
 Avatar = "images/GabinoFanhunter.svg"
 ShowBio = true
 PermalinkText = "游댕"
 EmailAddress = "javinr@gmail.com"
 FacebookUser = "javinr"
 FlickrUser = "javinr"
 GitHubUser = "javinr"
 LinkedInUser = "javinr"
 TwitterUser = "nosoynuno"
 InstagramUser = "javinr"
 # These are parameters used for indieweb identity. You should set these along
 # with the above email/social network parameters.
[params.indieWeb]
 EmailAddress = "javinr@gmail.com"
 FacebookUser = "javinr"
 FlickrUser = "javinr"
 GitHubUser = "javinr"
 LinkedInUser = "javinr"
 TwitterUser = "nosoynuno"
 InstagramUser = "javinr"
 Country = "Espa침a"
 City = "Langreo"
 [params.endpoints]
   Auth = "https://indieauth.com/auth"
   Token = "https://tokens.indieauth.com/token"
